## Numpy Array Operations

In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("with Stap",arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
with Stap [2 4 6 8]
Negative Indexing 8


In [13]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element",arr_2d[1,2])
print("Entire row",arr_2d[1])
print("Entire column",arr_2d[:,1])

Specific element 6
Entire row [4 5 6]
Entire column [2 5 8]


## Sorting

In [ ]:
unsorted_arr=np.array([1,4,5,2,6,3,7,8])
print("Sorted array",np.sort(unsorted_arr))


arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis=0))

Sorted array [1 2 3 4 5 6 7 8]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


## Filter


In [18]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers %2 == 0]
print("Even numbers",even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [19]:
mask = numbers > 5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing  vs np.where()

In [ ]:
indices=[0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print("NP where",numbers[where_result])

[1 3 5]
No where [ 6  7  8  9 10]


In [32]:
condition_array = np.where(numbers > 5,numbers*2,numbers)
print(condition_array)
condition_array2= np.where(numbers > 5,"true","false")
print(condition_array2)

[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing data


In [36]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6 7 8]


## array compatibility

In [41]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.array([10,11,12,13])
print("compatibility shapes",a.shape == b.shape)
print("compatibility shapes",a.shape == d.shape)

compatibility shapes True
compatibility shapes False


## Compatibility shapes False


In [47]:
# np.vstack stacks arrays in sequence vertically (row wise)
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [50]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
