## Numpy array and basics
learn about numpy with chai aur code

In [5]:
import numpy as np

## creating array from list



In [18]:


arr_1d=np.array([1,2,3,4,5,6])
print("1d array:",arr_1d)


arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1d array: [1 2 3 4 5 6]
2D array: [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [19]:
py_list=[1,2,3]
print("Python list multiplication",py_list*2)

np_array=np.array([1,2,3]) #element wise multiplication
print("Python array multiplication",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time:",time.time()-start)

start=time.time()
np_array=np.arange(1000000) * 2
print("\n Numpy operation time:",time.time()-start)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time: 0.06080818176269531

 Numpy operation time: 0.003380298614501953


### Creating arrays from scratch


In [ ]:
# create an array of zeros with shape (3,4)
zeros = np.zeros((3,4))  # function for creating array of zeros by giving rows and columns
print("zeros array:\n", zeros)

# create an array of ones with shape (2,3)
ones = np.ones((2,3))  # function for creating array of ones
print("one array:\n", ones)

# create an array filled with the value 7, shape (2,2)
full = np.full((2,2), 7)  # function for creating array with a constant value
print("full array:\n", full)

# create an array with random values between 0 and 1, shape (2,3)
random = np.random.random((2,3))  # function for creating array with random values
print("random array:\n", random)

# create a sequence of numbers from 0 to 8 with step 2
sequence = np.arange(0, 10, 2)  # function for creating a sequence of numbers
print("sequence array:\n", sequence)



zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.97636769 0.66652389 0.59337717]
 [0.01719626 0.58241746 0.61828295]]
sequence array:
 [0 2 4 6 8]


### vector,Matrix and Tensor


In [ ]:
vector=np.array([1,2,3])
print("vector:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix:",matrix)
# vector: 1D array, represents a simple list of numbers (rank 1 tensor)
# matrix: 2D array, represents a table of numbers with rows and columns (rank 2 tensor)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor",tensor)

vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])# arr is a 2D numpy array with shape (2, 3)
print("shape", arr.shape)      # prints the shape of the array (rows, columns)
print("Dimension", arr.ndim)   # prints the number of dimensions (axes) of the array
print("size", arr.size)        # prints the total number of elements in the array
print("Dtype", arr.dtype)      # prints the data type of the array elements


shape (2, 3)
Dimension 2
size 6
Dtype int64


Array Reshaping

In [41]:
# create a 1D numpy array with values from 0 to 11
arr = np.arange(12)
print("Original array", arr)

# reshape the 1D array into a 2D array with 3 rows and 4 columns
reshaped = arr.reshape((3, 4))
print("reshaped array", reshaped)

# flatten the 2D array back to 1D (returns a copy)
flattened = reshaped.flatten()
print("\n Flattened array", flattened)

# ravel the 2D array back to 1D (returns a view if possible)
raveled = reshaped.ravel()
print("\n raveled array", raveled)


#Transpose
transpose=reshaped.T
print("\n Transposed array",transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
